#!/usr/bin/env bash

if [ ! -n "${MECHANIC_HOME+x}" ]; then

  PRG="$0"
  while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
    else
    PRG=`dirname "$PRG"`"/$link"
    fi
  done


  MECHANIC_HOME=`dirname "$PRG"`
  MECHANIC_HOME=`cd "$MECHANIC_HOME" && pwd`
fi

 
# build classpath from all jars in lib
if [ -f /usr/bin/cygpath ]; then
  CP=.
  for i in "$MECHANIC_HOME"/mechanic*.jar; do
    i=`cygpath --windows "$i"`
    CP="$CP;$i"
  done
  for i in "$MECHANIC_HOME"/lib/*.jar; do
    i=`cygpath --windows "$i"`
    CP="$CP;$i"
  done
else
  if [[ $(uname) = MINGW* ]]; then
    CP_SEPARATOR=";"
  else
    CP_SEPARATOR=":"
  fi
  CP=.
  for i in "$MECHANIC_HOME"/mechanic*.jar; do
    CP="$CP""$CP_SEPARATOR""$i"
  done
  for i in "$MECHANIC_HOME"/lib/*.jar; do
    CP="$CP""$CP_SEPARATOR""$i"
  done
fi

JAVA_OPTS="${JAVA_OPTS-}"

java -cp "$CP" $JAVA_OPTS org.lorislab.mechanic.Main ${1+"$@"}

