//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 10:26:32 PM CEST 
//


package org.lorislab.mechanic.xml.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="cli" type="{http://www.lorislab.org/mechanic/mechanic}FileType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="addSystemProperty" type="{http://www.lorislab.org/mechanic/mechanic}ChangeSystemPropertyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="removeSystemProperty" type="{http://www.lorislab.org/mechanic/mechanic}SystemPropertyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="updateSystemProperty" type="{http://www.lorislab.org/mechanic/mechanic}ChangeSystemPropertyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://www.lorislab.org/mechanic/mechanic}changeAttributes"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cli",
    "addSystemProperty",
    "removeSystemProperty",
    "updateSystemProperty"
})
public class Change {

    protected List<FileType> cli;
    protected List<ChangeSystemPropertyType> addSystemProperty;
    protected List<SystemPropertyType> removeSystemProperty;
    protected List<ChangeSystemPropertyType> updateSystemProperty;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "author", required = true)
    protected String author;
    @XmlAttribute(name = "profile")
    protected String profile;
    @XmlAttribute(name = "batch")
    protected Boolean batch;

    /**
     * Gets the value of the cli property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cli property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCli().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FileType }
     * 
     * 
     */
    public List<FileType> getCli() {
        if (cli == null) {
            cli = new ArrayList<FileType>();
        }
        return this.cli;
    }

    /**
     * Gets the value of the addSystemProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addSystemProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddSystemProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChangeSystemPropertyType }
     * 
     * 
     */
    public List<ChangeSystemPropertyType> getAddSystemProperty() {
        if (addSystemProperty == null) {
            addSystemProperty = new ArrayList<ChangeSystemPropertyType>();
        }
        return this.addSystemProperty;
    }

    /**
     * Gets the value of the removeSystemProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the removeSystemProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRemoveSystemProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SystemPropertyType }
     * 
     * 
     */
    public List<SystemPropertyType> getRemoveSystemProperty() {
        if (removeSystemProperty == null) {
            removeSystemProperty = new ArrayList<SystemPropertyType>();
        }
        return this.removeSystemProperty;
    }

    /**
     * Gets the value of the updateSystemProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the updateSystemProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUpdateSystemProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChangeSystemPropertyType }
     * 
     * 
     */
    public List<ChangeSystemPropertyType> getUpdateSystemProperty() {
        if (updateSystemProperty == null) {
            updateSystemProperty = new ArrayList<ChangeSystemPropertyType>();
        }
        return this.updateSystemProperty;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the profile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfile() {
        return profile;
    }

    /**
     * Sets the value of the profile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfile(String value) {
        this.profile = value;
    }

    /**
     * Gets the value of the batch property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isBatch() {
        if (batch == null) {
            return true;
        } else {
            return batch;
        }
    }

    /**
     * Sets the value of the batch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBatch(Boolean value) {
        this.batch = value;
    }

}
