//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 10:26:32 PM CEST 
//


package org.lorislab.mechanic.xml.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.lorislab.mechanic.xml.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.lorislab.mechanic.xml.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ChangeLog }
     * 
     */
    public ChangeLog createChangeLog() {
        return new ChangeLog();
    }

    /**
     * Create an instance of {@link FileType }
     * 
     */
    public FileType createFileType() {
        return new FileType();
    }

    /**
     * Create an instance of {@link Change }
     * 
     */
    public Change createChange() {
        return new Change();
    }

    /**
     * Create an instance of {@link SystemPropertyType }
     * 
     */
    public SystemPropertyType createSystemPropertyType() {
        return new SystemPropertyType();
    }

    /**
     * Create an instance of {@link ChangeSystemPropertyType }
     * 
     */
    public ChangeSystemPropertyType createChangeSystemPropertyType() {
        return new ChangeSystemPropertyType();
    }

}
