//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.28 at 12:14:49 AM CEST 
//


package org.lorislab.mechanic.xml.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SystemPropertyValueType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SystemPropertyValueType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="HOST"/&gt;
 *     &lt;enumeration value="SERVER-GROUP"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "SystemPropertyValueType")
@XmlEnum
public enum SystemPropertyValueType {

    HOST("HOST"),
    @XmlEnumValue("SERVER-GROUP")
    SERVER_GROUP("SERVER-GROUP");
    private final String value;

    SystemPropertyValueType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SystemPropertyValueType fromValue(String v) {
        for (SystemPropertyValueType c: SystemPropertyValueType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
